### ISSUE TITLE
Exception thrown when comparing two values.

### ISSUE THREAD

**Issue by Romanx** [SteveDunn/Vogen#642]
### Describe the bug

An exception is thrown when performing a comparision between two well constructed objects. This only seems to happen if you use `ExcludeAssets="runtime"` in your PackageReference.

```
System.IO.FileNotFoundException: Could not load file or assembly 'Vogen.SharedTypes, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
  Stack Trace:
      at System.ModuleHandle.ResolveType(QCallModule module, Int32 typeToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCount, ObjectHandleOnStack type)
   at System.ModuleHandle.ResolveTypeHandle(Int32 typeToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)
   at System.Reflection.RuntimeModule.ResolveType(Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments)
   at System.Reflection.CustomAttribute.FilterCustomAttributeRecord(MetadataToken caCtorToken, MetadataImport& scope, RuntimeModule decoratedModule, MetadataToken decoratedToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, ListBuilder`1& derivedAttributes, RuntimeType& attributeType, IRuntimeMethodInfo& ctorWithParameters, Boolean& isVarArg)
   at System.Reflection.CustomAttribute.IsCustomAttributeDefined(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, RuntimeType attributeFilterType, Int32 attributeCtorToken, Boolean mustBeInheritable)
   at System.Reflection.CustomAttribute.IsDefined(RuntimeType type, RuntimeType caType, Boolean inherit)
   at System.Diagnostics.StackTrace.ToString(TraceFormat traceFormat, StringBuilder sb)
   at System.Diagnostics.StackTrace.ToString(TraceFormat traceFormat)
   at System.Exception.get_StackTrace()
```

### Steps to reproduce

Created a slimmed down repo project here: https://github.com/Romanx/VogenIssue

### Expected behaviour

The runtime asset can be excluded and no exception is thrown when comparing the two objects.

**Comment by SteveDunn** [comment]
Hi - thanks for the bug report.
By specifying `PrivateAssets="all" ExcludeAssets="runtime"`, you're saying that Vogen is a development-only dependency, which isn't strictly true. `Vogen.dll` **is**, but `Vogen.SharedTypes.dll` isn't.

The types specified in `VogenSharedTypes` need to be there at runtime because the generated code references them. For your scenario, the path through the generated code hits `EnsureInitialized`, which expects `ValueObjectValidationException` to exist:

```c#
        private readonly void EnsureInitialized()
        {
            if (!IsInitialized())
            {
#if DEBUG
                global::System.String message = "Use of uninitialized Value Object at: " + _stackTrace ?? "";
#else
                global::System.String message = "Use of uninitialized Value Object.";
#endif

                throw new global::Vogen.ValueObjectValidationException(message);  // <=== THROWN HERE
            }
        }
```
... but that exception isn't present at runtime.

You _could_ stop this from happening by specifying your own exception, e.g. in global config:
```c#
[assembly: VogenDefaults(throws: typeof(MyException))]
```

... but it is not recommended: doing so fixes your particular problem, but there are other shared types in `Vogen.SharedTypes`, such as `ValueObjectOrError` which is used if `TryFrom` is generated.

Including it adds just 18KB and one DLL to the published app:

<img width="238" alt="image" src="https://github.com/user-attachments/assets/6b66a6e6-d6dd-40ea-8e4a-66a2f03fc9c0">

Looking at it in something like dotPeek, you can see the types that it exports:

<img width="262" alt="image" src="https://github.com/user-attachments/assets/3dc1ea2f-82b2-4b85-9c59-af38d7cb823a">

I've updated [the wiki ](https://stevedunn.github.io/Vogen/installation.html)with this information.

Thanks again for your feedback.

**Comment by Romanx** [comment]
@SteveDunn thanks very much, we happily took the runtime dependency (which as you said is very small) when we found the error. Just got confused by the situation when it occurred. Thanks for updating the docs!
