### ISSUE TITLE
Conversions not being generation

### ISSUE THREAD

**Issue by adamhathcock** [SteveDunn/Vogen#77]
### Describe the bug

No EfCoreValueConverter being generated.

### Steps to reproduce

I have an Id struct like this:

```
  [ValueObject(conversions:Conversions.NewtonsoftJson | Conversions.EfCoreValueConverter, underlyingType:typeof(string))]
    public partial struct MyId { }
  ```

However, it appears there's no `new MyId.EfCoreValueConverter()` being generated.  I was attempting to follow https://github.com/SteveDunn/Vogen/blob/main/samples/Vogen.Examples/SerializationAndConversion/EfCoreExamples.cs

### Expected behaviour

`new MyId.EfCoreValueConverter()`  to exist

I'm unfamiliar with source generators so I though it might be because I'm not referencing EFCore where I was defining MyId but that doesn't seem to be the problem.  Pretty sure none are being generated.  What am I missing?

I'm using .NET 6

**Comment by SteveDunn** [comment]
Thanks for the bug report @adamhathcock - I'll take a look!

**Comment by SteveDunn** [comment]
@adamhathcock - if you click 'Show All Files' in Visual Studio's Solution Explorer window, you should be able to see the generated files:

![image](https://user-images.githubusercontent.com/263416/153401447-a32966c7-724a-4987-a280-7fe554cb43f0.png)

If you look in that file, you should see that it is generating the EFCore type:

![image](https://user-images.githubusercontent.com/263416/153402127-8d8f0666-498a-41b1-ab95-6baf9d24fb1a.png)

What do you see?

**Comment by adamhathcock** [comment]
I found the newtonsoft converter.

If I do `[ValueObject(conversions:Conversions.NewtonsoftJson | Conversions.EfCoreValueConverter, underlyingType:typeof(string))]` it doesn't generate the EFCore one

if I do `[ValueObject(conversions:Conversions.EfCoreValueConverter | Conversions.NewtonsoftJson, underlyingType:typeof(string))]` it generates both.  Seems like there is an actual bug.

I'm using RIder on MacOS so finding the generated files wasn't the same

**Comment by adamhathcock** [comment]
While we're doing requests :)

I'd like to do `.HasConversion<MyId.EfCoreValueConverter>()` instead of `.HasConversion(new Auth0Id.EfCoreValueConverter())`

EFCore6 uses a container and it wants a non-optional constructor

```
System.MissingMethodException: Cannot dynamically create an instance of type 'Disputed.Core.Model.Domain.Auth0Id+EfCoreValueConverter'. Reason: No parameterless constructor defined.
   at System.RuntimeType.ActivatorCache..ctor(RuntimeType rt)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type)
```

**Comment by SteveDunn** [comment]
I can't reproduce this on Windows. The tests pass on all platforms (Windows, Linux, MacOS).  I've added a bunch more tests to really stress it (combinations of types (class, struct, partial struct), underlying types (int, string, Guid, TimeSpan), and conversions (all permutations of them)

**Comment by SteveDunn** [comment]
When I use Rider (in Windows),  I can see:

![image](https://user-images.githubusercontent.com/263416/153718316-e7d2472b-55a8-4890-8bb9-7a1fbef4da8c.png)

**Comment by adamhathcock** [comment]
I can't reproduce the issue.  I'm guessing I was viewing something cached wrongly with the generated code.  I'm not sure.

Could have just been mistaken altogether 🤷 

And it looks like you're correct about my request.  It works when I pulled down your code.

I guess I'm still learning things.  Thanks for taking the time!

**Comment by SteveDunn** [comment]
Glad it's now working @adamhathcock - please do let me know if there's anything else wrong, or if you have any feature requests.
